### ISSUE TITLE
Audit History on Participant Details

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#105]
Audit History - confirm audit history is being saved. We need to know who edited the profile and when. Discuss with Bhaumik?

Audit History - if the audit history cannot be displayed when you leave and come back to the participant details page, remove the Audit History button for now and we'll make it post-MVP to add it back in. If it can be displayed when you leave and come back to the participant, make it readable in a way a study manager could understand it.

**Comment by brotzmanmj** [comment]
There is also a display of Last Modified By: at the bottom of the Participant Details page. We either need to get this to work and display actual saved data of who last edited the profile, or delete it from the page.

**Comment by abhinavjonnada82** [comment]
Audit History & Last Modified By hidden for now
<img width="1860" alt="Screen Shot 2021-06-05 at 3 45 00 PM" src="https://user-images.githubusercontent.com/30497847/120903600-ff4fd680-c614-11eb-89a4-37ce66445712.png">
