### ISSUE TITLE
Fix the Edit modal on Participant Details page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#106]
Fix the Edit modal so it says 'Edit' in the black and white space at the top

Then the variable should appear in the white space like this:
Preferred Name: [       ] and in the box, that's where they overwrite the existing name.

Then Comments: If the comments are not being stored, delete this box and we will add it to the post-MVP list of things needed.

**Comment by abhinavjonnada82** [comment]
Updated edit modal on Participant Details:
<img width="906" alt="Screen Shot 2021-06-05 at 3 30 27 PM" src="https://user-images.githubusercontent.com/30497847/120903227-f5c56f00-c612-11eb-880d-2c3c129736ed.png">
