### ISSUE TITLE
the concept id - 875549268 available in two places on participant record

### ISSUE THREAD

**Issue by dbakumar** [episphere/dashboard#11]
IHCS site send pre-consent max number of contact attempt reached status flag using submitParticipantsData API and will store inside state variable scope.  Looks another data item created with same concept id outside of state variable scope which create confusion.

![image](https://user-images.githubusercontent.com/4921186/113050050-087e7c00-916a-11eb-864a-3d6c1a2dfb31.png)

**Comment by bhaumik55231** [comment]
Thanks @dbakumar, I have fixed the issue. It was caused because we were trying to assign default values to some flags and this concept was being created in the non-state object instead of the state object.
