### ISSUE TITLE
Bug in Participant Look up

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#111]
From NORC testers:
On Participant Look-up:
When I filled in first name, last name, phone number and email, and hit search, it didn’t do anything - just returned to the screen with all the info filled in.  If I  filled  first name, last name, and either phone number or email, it returns the matching result.

**Comment by abhinavjonnada82** [comment]
API only accepts 3 parameters at once.

**Comment by brotzmanmj** [comment]
I was able to successfully search on 4 parameters at the same time: First name, last name, date of birth, and email. Can we discuss what the parameters are and why? I need a better understanding of this.

**Comment by abhinavjonnada82** [comment]
OR added to participant lookup:
<img width="1236" alt="Screen Shot 2021-06-07 at 1 48 42 PM" src="https://user-images.githubusercontent.com/30497847/121065718-14ed0980-c797-11eb-8f41-aaf381acef8e.png">
