### ISSUE TITLE
Remove asterisks from Withdrawal page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#113]
The asterisks don't signify anything now since the programming takes care of the checking of the right buttons.

**Comment by abhinavjonnada82** [comment]
Asterisks removed.
<img width="1737" alt="Screen Shot 2021-06-05 at 3 46 41 PM" src="https://user-images.githubusercontent.com/30497847/120903627-3a520a00-c615-11eb-8ad2-947de91350cb.png">
