### ISSUE TITLE
Fix display of metrics- age, sex, race

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#14]
The horizontal bars for the display of metrics on age, sex, race are expanding beyond the box and are not visible. Also the hover overlaps so much among categories that it's not readable.

**Comment by abhinavjonnada82** [comment]
_horizontal bars for the display of metrics on age, sex, race are expanding beyond the box and are not visible_. Its not happening on my screen. Could you please mention your screen size & resolution.

This is due to small size of the container and with lot of things to display everything is cramped into a small space. I can remove the hovers and add a legend.

**Comment by abhinavjonnada82** [comment]
Done.

**Comment by abhinavjonnada82** [comment]
<img width="1792" alt="Screen Shot 2021-04-07 at 11 33 18 AM" src="https://user-images.githubusercontent.com/30497847/113893525-1d27c900-9795-11eb-829e-2ae112b0cc5f.png">

**Comment by brotzmanmj** [comment]
Mine is still looking problematic. 
![image](https://user-images.githubusercontent.com/53540067/114069932-82e78400-986d-11eb-95a1-5b09efa78f38.png)

**Comment by brotzmanmj** [comment]
let's await feedback from the sites as more data accumulates and then decide if we need to change to legend.

**Comment by abhinavjonnada82** [comment]
Sounds good!

**Comment by FrogGirl1123** [comment]
Depending on the feedback from the sites, my suggestion would be to have a color legend to the right of the figure like we do for the pie charts,  show the percent within each bar segment and then show the count if you hover.

**Comment by robertsamm** [comment]
@abhinavjonnada82 HPs feedback is to break up the age, sex, and race verified pt demographics into active vs passive recruits.
If we are able to implement this, we would want to keep the figures as horizontal bars. And I like @FrogGirl1123 suggestion of using a legend that shows the count if you hover.

If we are not able to split it up into active vs. passive then HP recommends we change the figures to 3 pie charts - 1 for age, 1 for sex, 1 for race.

**Comment by robertsamm** [comment]
@abhinavjonnada82 Also, can you check that the data for age, sex, and race is getting pulled from the de-identified demographic data that the site sends to us and not the responses from the module 1 survey (background and overall health)? This may be why the numbers aren't matching up with the total number of verified participants.

![image](https://user-images.githubusercontent.com/67074735/115457316-5d099a00-a1f2-11eb-80ce-9dfe2240773c.png)

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by brotzmanmj** [comment]
Discussed at meeting 5/17 with Mia and Nicole. Change the three horizontal bars to three pie charts. One for sex, one for race, one for age. Include a legend for each. Use the same type of display with the N= and the percent like you have for the verification status pie charts. Do not split up into active vs passive. We will capture that in the weekly reports.

**Comment by brotzmanmj** [comment]
Display just the harmonized variables, not the site specific ones. Madhuri has provided the harmonization code in the MVP metrics spreadsheet.
The title for the age pie chart should be 'Age of Verified Participants N='
The title for the race pie chart should be 'Race/Ethnicity of Verified Participants N= '
The title for the sex pie chart should be 'Sex of Verified Participants N='

**Comment by abhinavjonnada82** [comment]
Updated charts:
<img width="1756" alt="Screen Shot 2021-07-08 at 12 33 49 AM" src="https://user-images.githubusercontent.com/30497847/124862886-2d159b80-df84-11eb-8624-e27e5a9b499f.png">

**Comment by brotzmanmj** [comment]
Hi Abhinav, We are getting closer! However, there are 63 verified participants, so why the difference in the counts?
