### ISSUE TITLE
Fix metric for active recruits verification status

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#15]
The counts displaying in this pie chart in the HP end to end testing aren't correct

**Comment by abhinavjonnada82** [comment]
I can verify the results & query.

**Comment by FrogGirl1123** [comment]
The counts are also incorrect in the pie chart for the passive recruits.

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by abhinavjonnada82** [comment]
![Screen Shot 2021-04-28 at 2 26 33 PM](https://user-images.githubusercontent.com/30497847/116454702-45539680-a82e-11eb-8e4c-43097b134011.png)

28.57 is
const cannotBeVerified = activeVerificationStatus.cannotBeVerified 
 && ((activeVerificationStatus.cannotBeVerified)/(denominatorVerificationStatus.activeDenominator)*100).toFixed(2);
 

33.33% is the percentage area of the pie (33.33 + 16.7 + 50 = 100%)

**Comment by abhinavjonnada82** [comment]
<img width="596" alt="Screen Shot 2021-04-29 at 3 34 33 PM" src="https://user-images.githubusercontent.com/30497847/116607776-671d4e00-a900-11eb-964d-1026027cf417.png">

**Comment by robertsamm** [comment]
@abhinavjonnada82 sorry Abhinav, reopening this issue. It looks like the percents showing in the hover are not the same as the percents in the wedges again. It looks like the wedges are accurate, can we just take the percent on the hover off completely? For both active and passive

![image](https://user-images.githubusercontent.com/67074735/117463671-ef61ab80-af1d-11eb-8e09-ee57315763cd.png)

**Comment by abhinavjonnada82** [comment]
Health Partners Active Verification Pie Chart
<img width="575" alt="Screen Shot 2021-05-10 at 7 12 27 PM" src="https://user-images.githubusercontent.com/30497847/117735547-aa5ea300-b1c3-11eb-8c96-713cf44d7ac1.png">
<img width="582" alt="Screen Shot 2021-05-10 at 7 12 37 PM" src="https://user-images.githubusercontent.com/30497847/117735560-b21e4780-b1c3-11eb-9714-8cb342f88724.png">
<img width="580" alt="Screen Shot 2021-05-10 at 7 13 08 PM" src="https://user-images.githubusercontent.com/30497847/117735593-c2362700-b1c3-11eb-8675-470f277f0d57.png">
<img width="572" alt="Screen Shot 2021-05-10 at 7 13 19 PM" src="https://user-images.githubusercontent.com/30497847/117735604-c8c49e80-b1c3-11eb-831e-dbd2df810f72.png">
<img width="588" alt="Screen Shot 2021-05-10 at 7 12 52 PM" src="https://user-images.githubusercontent.com/30497847/117735577-b9455580-b1c3-11eb-847a-bff21811e361.png">

**Comment by robertsamm** [comment]
@abhinavjonnada82 Just looked at the pie charts for NCI dshbrd and the %'s still don't match. Can we take the the %'s off the hover?
![image](https://user-images.githubusercontent.com/67074735/118173377-7a014980-b3fb-11eb-9529-c111cab10eab.png)

**Comment by brotzmanmj** [comment]
Checked these for a number of sites this evening at 5pm and the data in them are still not accurate

**Comment by abhinavjonnada82** [comment]
For ALL sites
![Screen Shot 2021-05-20 at 10 49 29 AM](https://user-images.githubusercontent.com/30497847/119000400-14f8a700-b959-11eb-840a-44f24eafb077.png)

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 @brotzmanmj @robertsamm  Be sure to use sites with good data to test code for the metrics.  Sanford has the best, most complete data, followed by Marshfield.  KP and HP have issues that will affect your results.  NCI also shouldn't be used because of other testing going on.  So I would wait to adjust the ALL sites metrics until we start the next round of testing and don't use KP, HP, or NCI to check your code.
