### ISSUE TITLE
Freezer header row on search results page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#16]
On the page with the participants search results (which also serves as the page with filtering by all participants, not yet verified participants, verified participants, etc), freeze the header in the table so when you scroll down you can still see it

**Comment by abhinavjonnada82** [comment]
DONE. Will be added to the next PR

**Comment by abhinavjonnada82** [comment]
<img width="1783" alt="Screen Shot 2021-04-07 at 11 34 25 AM" src="https://user-images.githubusercontent.com/30497847/113893638-36c91080-9795-11eb-9865-1d93d98c44d3.png">
