### ISSUE TITLE
Gray out the edit buttons on the Pt Details page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#17]
On the Participant Details page, the blue 'Edit' box is not obvious that you cannot edit if the person has been verified. Can we change color to gray instead of light blue to make it clearer? Is that 508 compliant?

**Comment by abhinavjonnada82** [comment]
DONE. I believe GRAY color is 508 compliant.
http://web-accessibility.carnegiemuseums.org/design/color/

**Comment by abhinavjonnada82** [comment]
<img width="1251" alt="Screen Shot 2021-04-07 at 11 41 54 AM" src="https://user-images.githubusercontent.com/30497847/113894695-41d07080-9796-11eb-9215-5d75aa34e8be.png">
