### ISSUE TITLE
Date of death on participant withdrawal page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#170]
@abhinavjonnada82 When testing the participant withdrawal options for 'deceased' in dev I notice that the suggested input for day of death says "select birth day" this should just say "select day". 

![image](https://user-images.githubusercontent.com/67074735/128570423-da611479-c144-422c-91a3-4c44833a2aab.png)

**Comment by abhinavjonnada82** [comment]
<img width="897" alt="Screen Shot 2021-08-09 at 6 47 14 PM" src="https://user-images.githubusercontent.com/30497847/128783725-001ff7e6-6b75-45bc-be4c-8a871c17ade6.png">
