### ISSUE TITLE
Submit issue for 'deceased' participant on date of death page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#171]
@abhinavjonnada82 When testing the participant withdrawal page for a 'deceased participant' it is not allowing me to move forward on the day of death page. When I click 'submit' it does not submit the page.

![image](https://user-images.githubusercontent.com/67074735/128570721-559d627c-d6c9-41d5-89c5-8b65b2cadb55.png)

**Comment by abhinavjonnada82** [comment]
It should be working now!
