### ISSUE TITLE
check marks for revocation and data destruction

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#173]
Hi @abhinavjonnada82. For HIPAA revocation and data destruction on the participant summary page. We noticed that there are green check marks for participants that requested revocation/destruction but did NOT sign the form yet. Can we change this so they reflect the status of the form where (signed = green check, not signed = red X)?

![image](https://user-images.githubusercontent.com/67074735/128764549-b248d4a1-9d7b-467f-85d7-ad503a41eba1.png)

**Comment by abhinavjonnada82** [comment]
@robertsamm I believe Michelle wanted a check sign when some one has initiated HIPAA revocation or data destruction irrespective of if they signed or not signed.

**Comment by brotzmanmj** [comment]
Amelia is correct, we want the markings to reflect whether or not they have signed the form

**Comment by abhinavjonnada82** [comment]
<img width="1766" alt="Screen Shot 2021-08-10 at 9 51 24 AM" src="https://user-images.githubusercontent.com/30497847/128879073-2e2786b1-3cee-4026-9ea7-55182807aea9.png">

**Comment by robertsamm** [comment]
@abhinavjonnada82 For test participant Connect ID: 6223902315 data destruction form is showing as not signed even though it was signed in the PWA. Seems to be a PWA issue (https://github.com/episphere/connectApp/issues/227). Once that issue is fixed, need to retest on SM dashboard pt summary page 

![image](https://user-images.githubusercontent.com/67074735/128890895-fc9bb08f-d10d-4817-851d-414cfcdfff82.png)
