### ISSUE TITLE
Pre-consent opt out field not populating

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#185]
In Dev, look at Study ID: MC000011A111410 

When you select Pre-Consent Opt Out to show in the 'All Participants' list, it should show 'Yes' for this study id but does not.

**Comment by abhinavjonnada82** [comment]
> @abhinavjonnada82 Pre-consent opt-out field is working fine now. Date/time for pre-consent opt out field does not seem to be populating

This data is sent from the sites

**Comment by brotzmanmj** [comment]
@FrogGirl1123 Hi Nicole, can you tell us whether the date/time of pre-consent opt out is supposed to be sent by the site, or whether our system is supposed to set that date/time stamp upon receipt of a pre-consent opt out from the site?

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 @brotzmanmj It's supposed to be set by us upon receipt

**Comment by brotzmanmj** [comment]
@abhinavjonnada82 I think we should be populating this date/time stamp upon receipt for the pre-consent opt out flag on our side. Discuss with Bhaumik next?

**Comment by bhaumik55231** [comment]
Hi Michelle, @brotzmanmj is this the correct concept 697256759?

Hi Nicole, @FrogGirl1123 The opt-out concept - 158291096 is stored as a default variable so the sites will need to use updateParticipantData API to update its value from No (104430631) to Yes (353358909). And that is when we can assign an opt-out timestamp.

**Comment by brotzmanmj** [comment]
@bhaumik55231 Hi Bhaumik, yes, that's the correct concept ID for the date/time stamp of opt out

**Comment by FrogGirl1123** [comment]
@brotzmanmj In the sense that we are clearing up confusion regarding which API the sites need to send the data through, yes.  @bhaumik55231 and @abhinavjonnada82 is is good on your end?
