### ISSUE TITLE
Add verification table variables to participant list page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#186]
Variables from the verification table are not on the Participant list page, but the site users have requested to have them added. Madhuri will provide the list of which are the variables to add. Please put them right after Verification date/time.

**Comment by mnataraj92** [comment]
@brotzmanmj  @abhinavjonnada82  they're rows 288-316 in the master dictionary
RcrtV_Automated_v1r0
RcrtV_Outreach_v1r0
RcrtV_Mannual_v1r0
RcrtV_DuplicateType_v1r0
RcrtV_UpdateRecType_v1r0
RcrtV_FNameMatch_v1r0
RcrtV_LNameMatch_v1r0
RcrtV_DOBMatch_v1r0
RcrtV_PINMatch_v1r0
RcrtV_TokenMatch_v1r0
RcrtV_ZipMatch_v1r0
RcrtV_SiteMatch_v1r0
RcrtV_AgeMatch_v1r0
RcrtV_CStatusMatch_v1r0

**Comment by robertsamm** [comment]
@abhinavjonnada82 please place these variables after the 'Verification Status Time' var on the participants page.

**Comment by abhinavjonnada82** [comment]
3 'duplicate type' variables removed:


<img width="1727" alt="Screen Shot 2021-08-30 at 5 30 42 PM" src="https://user-images.githubusercontent.com/30497847/131408354-a80ab8bc-c4ca-41ba-9f47-f9ed69d882b2.png">
