### ISSUE TITLE
Refusal/Withdrawl Timestamp variables missing from participants table

### ISSUE THREAD

**Issue by mnataraj92** [episphere/dashboard#195]
These timestamp variables are missing from the participants table:
HdRef_DateBasesrv_v1r0
HdRef_DateBaseblood_v1r0
HdRef_DateBaseurine_v1r0
HdRef_DateBasesaliva_v1r0
HdRef_DateAllsrv_v1r0
HdRef_DateAllsample_v1r0
hdref_blspecsrvdt_v1r0
HdWd_DateActivepart_v1r0

**Comment by abhinavjonnada82** [comment]
<img width="789" alt="Screen Shot 2021-08-29 at 9 06 56 PM" src="https://user-images.githubusercontent.com/30497847/131272026-beadf849-8acb-4701-8b3e-e6148e71eac6.png">

**Comment by abhinavjonnada82** [comment]
<img width="858" alt="Screen Shot 2021-08-29 at 9 07 22 PM" src="https://user-images.githubusercontent.com/30497847/131272051-87692809-9abd-477b-a08c-ead317526814.png">

**Comment by abhinavjonnada82** [comment]
I was able to capture all of them except this following:
883668444 as HdWd_DestroyDataCat_v1r0
304438543 as HdWd_DestroyDataVer_v1r0
104278817 as HdWd_FnameDD_v1r0
744604255 as HdWd_LnameDD_v1r0
268665918 as HdWd_MnameDD_v1r0
592227431 as HdWd_SuffixDD_v1r0
577794331 as HdWd_HIPAARevokedCat_v1r0
407743866 as HdWd_HIPAArevokedver_v1r0
765336427 as HdWd_Fname_v1r0
479278368 as HdWd_Lname_v1r0
826240317 as HdWd_Mname_v1r0
693626233 as HdWd_Suffix_v1r0
161366008 as HdWd_SuspendDt_v1r0

Not sure if Participant Withdrawal is a right place to set the values.

**Comment by brotzmanmj** [comment]
I believe all of these except 161366008 as HdWd_SuspendDt_v1r0 have to do with signing the form(s) which is done in the MyConnect app so I agree with Abhinav it seems these values should be set by Brian via the app. 

I'm pretty certain 161366008 as HdWd_SuspendDt_v1r0 gets set on the refusal/withdrawal page on the Study Manager Dashboard.

**Comment by brotzmanmj** [comment]
@abhinavjonnada82 This is awaiting clarification from Brian as to whether/where those variables upon form signing are being stored.

**Comment by naiyume** [comment]
I agree that these should be stored on the PWA side. Will add these variables to PWA.

**Comment by robertsamm** [comment]
@abhinavjonnada82 @bhaumik55231 @naiyume Hi all, we are concerned these variables, while seem to be storing correctly in dev, may not have been pushed to stage or prod. Can you please double check this? @mnataraj92 can provide more info if needed.

**Comment by mnataraj92** [comment]
Yes- we just want to double check and make sure that they've been pushed to stage and prod, and that the reason that they're not showing up in the participants table in either environment is because we don't have data for those variables yet.

**Comment by abhinavjonnada82** [comment]
These changes are pushed to stage & prod.

**Comment by mnataraj92** [comment]
@robertsamm @abhinavjonnada82 all of the pre-consent opt-out variables are now all in the participants table for dev/stage/prod. The only variable I don't see yet though is RcrtSI_OptOutTm_v1r0 (concept ID 697256759) which is the date/time for pre-consent opt-out.
