### ISSUE TITLE
Duplicate notifications being sent out

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#196]
Bug on SM dshbrd causing duplicate notifications to be sent to participants when the schema is updated more than once. It is creating a new schema record instead of updating it.

This is high priority because right now test participants who withdrew from the study are receiving post-verification emails asking them to complete the surveys. We don't want this to happen in prod.

**Comment by abhinavjonnada82** [comment]
Issue has been fixed @robertsamm you can use Notification schemas (category: "test-qwerty" , category: "test-aj" ) for testing. Once done let me know, I'll delete them.

**Comment by depietrodeanna** [comment]
@abhinavjonnada82 Issue fixed! please delete the test schemas
