### ISSUE TITLE
Display actual responses rather than concept IDs throughout

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#20]
On all dashboard pages, display the actual categorical responses rather than the concept IDs. For example display 'Yes' instead of the concept ID for 'Yes'. This is needed for variable labels as well as responses. For another example, click the 'Show all Info' button on the participant search results screen. It needs to show the variable label and the variable response code as opposed to the concept IDs. This is true anywhere a concept ID currently appears on the SM Dashboard.

**Comment by abhinavjonnada82** [comment]
Need to finalize a list of items that need to be displayed.

**Comment by brotzmanmj** [comment]
Yes, for the See all items we need to decide what to display. But if they click on a data element at the top of the screen in order to display it in the table below, when it displays it needs to show the response in words rather than the concept ID. Can we work on that part?

**Comment by brotzmanmj** [comment]
Decided at meeting on 6/3 to hide the 'Show All Info' column in the table

**Comment by abhinavjonnada82** [comment]
'Show All Info' column hidden in the table:
<img width="1749" alt="Screen Shot 2021-06-05 at 3 01 30 PM" src="https://user-images.githubusercontent.com/30497847/120902535-eb08db00-c60e-11eb-866b-5844f64070c9.png">
