### ISSUE TITLE
Add filter by site function to 'Verified Participants' page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#200]
Can we add the 'filter by site' function/button to the 'Verified Participants page? It is currently only on the 'all participants' page. 

![image](https://user-images.githubusercontent.com/67074735/131900655-65a82dff-abfc-442d-8059-07cc0c506f8e.png)

**Comment by abhinavjonnada82** [comment]
Duplicate issue created: https://github.com/episphere/dashboard/issues/399
