### ISSUE TITLE
Relabel 'Text' on Participant Details page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#21]
In the column 'Field', there is a label called 'Text' which I think is supposed to mean 'Do we have permission to text this number'? but is not clear if that's what it is. If so, please relabel it.

**Comment by abhinavjonnada82** [comment]
<img width="1785" alt="Screen Shot 2021-04-07 at 12 57 19 PM" src="https://user-images.githubusercontent.com/30497847/113905110-cb853b80-97a0-11eb-9f0c-926ad3490eae.png">
