### ISSUE TITLE
Check if 'Other Phone' and 'Preferred Contact Method' are working

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#22]
On Participant Details page, there are always blank responses to 'Other phone' and 'preferred contact method'. Is that because HP didn't enter any information for these fields or because they are not capturing and rendering data correctly?

**Comment by abhinavjonnada82** [comment]
DONE.

**Comment by abhinavjonnada82** [comment]
<img width="1785" alt="Screen Shot 2021-04-07 at 12 57 19 PM" src="https://user-images.githubusercontent.com/30497847/113905110-cb853b80-97a0-11eb-9f0c-926ad3490eae.png">

**Comment by abhinavjonnada82** [comment]
For other phone, I'm pointing to the right variable but I dont think any response is returned for other phone and voicemail

**Comment by brotzmanmj** [comment]
Could you check with Nicole and Madhuri on this?

**Comment by abhinavjonnada82** [comment]
Variables aren't being collected on the back end and issues has been raised.

**Comment by brotzmanmj** [comment]
Is Brian aware and working on a fix for this?

**Comment by abhinavjonnada82** [comment]
I can check with him
