### ISSUE TITLE
Site acronym on site messages page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#222]
The "site acronym" for all of the site messages appearing in the stage SM dshbrd have 'NIH' as the value. This should actually be the site the message is being sent to (in the example below it should be UChicago). This should be fixed in dev as well if necessary, but I don't see any site messages in dev to check this right now.

![image](https://user-images.githubusercontent.com/67074735/137027009-acc06fc1-041e-405f-b933-66e4f044a485.png)

**Comment by abhinavjonnada82** [comment]
Bhaumik advised to have the Site Acronym removed on the UI side. It is useful only on the back end.
