### ISSUE TITLE
Fix a few icons on the Pt Summary page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#24]
The icon for Consent on Participant Summary page is showing as a green checkmark even though it is not completed. 

The icon for Baseline Blood is also showing as 'Collected' for participant that has not been verified. Is this pointing to just a placeholder? Can it be pointed to the real variable now instead?

**Comment by abhinavjonnada82** [comment]
Error was fixed on Consent. For baseline blood, yes it is pointing to placeholder. Right variable is used and let me check if there's any data available on the variable.

**Comment by abhinavjonnada82** [comment]
<img width="1770" alt="Screen Shot 2021-04-07 at 11 41 04 AM" src="https://user-images.githubusercontent.com/30497847/113894572-24030b80-9796-11eb-8f99-b360c79f0a95.png">

**Comment by brotzmanmj** [comment]
Confirmed the consent icon is fixed. Will leave this issue here until we're able to fix the Blood Collected icon.

**Comment by abhinavjonnada82** [comment]
sounds good!
