### ISSUE TITLE
DEPRECATED- Nesting of "Who Requested" variable

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#243]
We need to change the "who requested" refusal/withdrawal variable so that it is nested where we will store multiple responses for if a pt has a refusal/withdrawal requested at different times/more than once. Right now it is storing only one time.

@mnataraj92 please add more info, if needed. Once it is nested we will need to test.

**Comment by mnataraj92** [comment]
@robertsamm @robertsamm Once NORC sends out a scenario with different people requesting refusal/withdrawal at different times, we can see how it's being stored. If it's not storing as a repeated measures variable, then it'll need to be changed.

**Comment by robertsamm** [comment]
@mnataraj92 Hi Madhuri, I just pushed a second refusal for one of the participants NORC tested with a different selection for "who requested". 

Connect ID: 9597590611
First time: refused all future surveys at 19OCT21:18:59:34 and selected "the participant" for who requested
Second time: withdrew consent and revoked HIPAA at 2021-11-05T19:01:26.361Z and selected "The Connect Principal Investigator (or designate)" for who requested

**Comment by mnataraj92** [comment]
Hi @robertsamm , 

I ran the query for that Connect ID, and for some reason, it marked withdrawing consent and revoking HIPAA as "no". The concept ID for who requested the refusal/withdrawal corresponds to the participant. 
<img width="676" alt="Query" src="https://user-images.githubusercontent.com/76711181/140568151-4cb9f647-2663-46a9-91d7-7051ecbd1608.png">
<img width="569" alt="Query Result" src="https://user-images.githubusercontent.com/76711181/140568159-1f48268b-9237-4baa-a942-3a91402fb740.png">

**Comment by robertsamm** [comment]
Hi @mnataraj92 Looking at the dshbrd it is showing withdraw consent and revoke HIPAA both = yes. Could it be that the data hasn't synced yet? Like for the thing where Bhaumik decreased the time from 4 hours to 1 hour?

![image](https://user-images.githubusercontent.com/67074735/140568807-7b19f6cc-3fd6-4074-9ccd-333aeb630c16.png)

**Comment by mnataraj92** [comment]
@robertsamm Oh that could be it! I can check it by COB and if it hasn't updated then I can check it Monday morning.

**Comment by mnataraj92** [comment]
Hi @robertsamm 
I just re-ran the query and the data updated. For who requested, it's only showing the participant, so I don't think it's being stored as a repeated measures variable
<img width="680" alt="queryresult" src="https://user-images.githubusercontent.com/76711181/140753366-ec99b416-0af4-42de-85ab-a68c77289646.png">
.

**Comment by robertsamm** [comment]
@mnataraj92 @FrogGirl1123 Hi Nicole and Madhuri, what are the next steps for this? Do you need to change the variable so that it's nested?

**Comment by mnataraj92** [comment]
@robertsamm we discussed potential solutions for this to be stored as a repeated measures variable at the end of one of our meetings on Wednesday with Abhinav, Brian, and Bhaumik, and I think this is still in progress.

**Comment by FrogGirl1123** [comment]
Hi All,

Based on the testing of the refusal/withdrawal dashboard this still needs work.  As we discussed on the Punch list call this morning, @abhinavjonnada82 Abhinav will provide the current JSON for how the data is nested so that @FrogGirl1123 can give feedback on how it should be nested.  @Davinkjohnson will include this item in the Prep meeting on 12/14

**Comment by abhinavjonnada82** [comment]
Connect_ID : 3217391091
Selected Refusal Option(s): Baseline Blood Donation, Baseline Urine Donation, Baseline Mouthwash (Saliva) Donation, Revoke HIPAA Authorization, Withdraw Consent​, Destroy Data​
<img width="1361" alt="Screen Shot 2021-12-14 at 9 31 51 AM" src="https://user-images.githubusercontent.com/30497847/146017748-bbffd20b-2538-4b99-b313-d7424dd080af.png">
<img width="272" alt="Screen Shot 2021-12-14 at 9 37 53 AM" src="https://user-images.githubusercontent.com/30497847/146018979-5ffbe091-4ab6-4096-8025-879eeab12ba4.png">

**Comment by FrogGirl1123** [comment]
We are reverting to the previous structure due to downstream issues with the nested changes. @abhinavjonnada82 I don't know if a new issue has been created for the rollback or not.  If so we should close this issue and breakout the related tasks for the rollback into new issues.
