### ISSUE TITLE
Remove verify/can't verify buttons on the participant search results screen

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#25]
If you scroll all the way over on the participant search results screen (the one where you can display the list of verified, not yet verified, etc participants), there is an option that allows the user to click 'verify' or 'can't verify'. That functionality should no longer exist. Please remove. FYI: The 'verify/can't verify' buttons only appear if you filter on 'Not Yet Verified' at the top.

**Comment by abhinavjonnada82** [comment]
I can see 'verify/can't verify' buttons only on 'Not Yet Verified' page and don't see them on others. Would you mind adding few screenshots please.

**Comment by brotzmanmj** [comment]
I also see them only on 'Not yet verified' page. I  remembered now I think they are here because we need them temporarily for the NCI site to be able to verify people since we have no other way to do so, for testing purposes. Before we move this to production, we need to remove them. Should we leave this issue open so we remember to do this?

**Comment by abhinavjonnada82** [comment]
Yah absolutely! I added a tag as a reminder.
