### ISSUE TITLE
Load each page at the top

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#26]
After selecting a participant in the search and then go to the Pt Details or Pt Summary, it should go to the top of the page.

**Comment by abhinavjonnada82** [comment]
After selecting a participant in the search and the page on both Participant Details & summary go to the top of the page. Could you please record the issue and post it here?

**Comment by brotzmanmj** [comment]
Here is example: When I select participant Handd from the search results, it takes me to the middle of the Participant Details page instead of the top:
![image](https://user-images.githubusercontent.com/53540067/114079154-d363df00-9877-11eb-8117-8ecc2d8f2ab1.png)

**Comment by abhinavjonnada82** [comment]
I don't see this behavior on my screen. But nevertheless, I added a code check to prevent such behavior.
       ` document.body.scrollTop = document.documentElement.scrollTop = 0;`
