### ISSUE TITLE
NCI appearing as site in prod and stage

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#263]
@abhinavjonnada82 @Davinkjohnson Today I noticed that NCI is appearing as a site in the prod and stage versions of the Study Manager Dashboard. I thought that was only supposed to exist in Dev. Did this get changed accidentally as part of the latest release?

**Comment by abhinavjonnada82** [comment]
Moving forward NCI would only appear in  DEV.

**Comment by robertsamm** [comment]
@abhinavjonnada82 I still see NCI listed as a site under the 'filter by site' filters on the home metrics page and the all participants page
