### ISSUE TITLE
pagination and filtering problem in dev

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#272]
@abhinavjonnada82  HI Abhinav, on the study manager dashboard in dev, when I filter on a site and then change the pagination (say, to 25 or 50 or 100) it loses the site filter and loads participants from all sites. And then if I go back up and try to filter on a site again, it  resets the pagination back to 10. 
Also when I click Next and Back on the pagination, it loses the site filter.

**Comment by abhinavjonnada82** [comment]
Solution Deployed.
