### ISSUE TITLE
Data destruction pt emails issues

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#275]
There are a couple of issues with the data destruction message I received for one of my test participants (Connect ID: 1733465133).

1. The data destruction email went to my spam inbox. The other two emails (magic link, verified BL survey) went to my promotions folder. Which is also different from how the emails went with my other test participant. For that one - the magic link went to my promotions folder, and the other 2 emails (verified baseline survey, withdrawal/revocation) went in my primary inbox. Both with Gmail.

2. MyConnect ID is showing right before the first sentence. The ConnectID should not be showing in any of the participants messages.

![image](https://user-images.githubusercontent.com/67074735/151202515-32969442-d407-45c6-9569-c9ef91287689.png)

**Comment by depietrodeanna** [comment]
For #2, removed the Connect ID from notification specs. Should no longer appear in data destruction emails.
