### ISSUE TITLE
Fix link to KBA for app download instructions in prod

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#277]
This is to track the issue discussed yesterday and document its resolution. In the prod survey reminder email message content for Contact1, there was an outdated link to a KBA on the NORC CSC website with instructions about how to download the app. The KBA pointed to the dev version of the app as opposed to the prod version. The KBA was marked as outdated and a link provided to the current KBA with the correct link to the prod version of the app. No prod users accessed the dev version of the app.

@depietrodeanna will do the following:
1) Replace the URL in the prod message with the correct URL and save.
2) Check the second contact attempt in the survey reminder series and make sure it has a link to download the app and that it has the correct URL
3) Notify NORC ASAP to request removal of the old KBA and to request they check all KBAs for similar issues.
4) Check all hyperlinks on existing message specs in prod and make sure each one takes the user to the right place
5) Draft an SOP for message development and implementation including a checklist for each major step in the process from message construction and conditionality, to testing, to going to prod.

**Comment by depietrodeanna** [comment]
Update 1/27/2022- #1 complete, #2 complete
Update 1/28/2022- #3 complete 

In progress: #4 and #5
