### ISSUE TITLE
Fix 'submitted' label 'Cumulative Status' 

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#28]
On the 'Cumulative Status' variable, there is a label 'Submitted'. This refers to the User Profile Submitted which is too long to display, but 'Submitted' alone is confusing. Please change to 'Profile Done'- will that fit?

**Comment by abhinavjonnada82** [comment]
Done. It fits well!

**Comment by abhinavjonnada82** [comment]
<img width="607" alt="Screen Shot 2021-04-07 at 11 46 04 AM" src="https://user-images.githubusercontent.com/30497847/113895301-d6d36980-9796-11eb-93f7-a34009a15f87.png">
