### ISSUE TITLE
Pt Pg Filtering - adding fields cancels filtered list

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#288]
When the list is filtered by active/passive and/or date, unable to add additional fields without it reverted back to unfiltered list.

**Comment by robertsamm** [comment]
Hi @abhinavjonnada82 I can now add fields at the top and it will keep the filtered list which is what we wanted, BUT it keeps reverting the number of records displayed back to the default of 10 (e.g. I selected show 100 records > select a filter it reverts back to 10; or I already have the list filtered > select show 100 records > and select a field from above and it reverts back to 10).

**Comment by abhinavjonnada82** [comment]
Deployed on PROD.
