### ISSUE TITLE
Pt Pg Filtering - Still see records when no results found

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#289]
If no records are available when filtering by “active” or “passive” or by "date" filter should have the list show zero records. Right now it shows a message that says “No results found!” but keeps the list of records that were showing before selecting filter on the screen.

**Comment by robertsamm** [comment]
Hi @abhinavjonnada82 this seems to be working correctly when I use the site keys to just look at the site dshbrds. But in the parent/NCI dshbrd there seems to be an issue now that whenever I select the "active" or "passive filters" when I am already filtered down to a particular site, it ends up showing me all of the active or passive records for all of the sites, not the one it is filtered on.

Example #1: Selected KPGA which has both active and passive records > then selected "active" now showing me active records for all of the sites not just KPGA
![image](https://user-images.githubusercontent.com/67074735/156451550-4179427e-aeaf-498e-ad36-d245a16d8bef.png)

Example #2: Selected UofC which I know only has passive records > then selected "active" > with the fix above it should show me zero records but it jumps to showing me all sites with passive records
![image](https://user-images.githubusercontent.com/67074735/156452039-41aeabc5-c8c0-444a-a06a-a5f458c7bbe4.png)

**Comment by abhinavjonnada82** [comment]
Issue fixed.

**Comment by abhinavjonnada82** [comment]
Deployed on PROD.
