### ISSUE TITLE
Source of Deceased Report (764403541)

### ISSUE THREAD

**Issue by mnataraj92** [episphere/dashboard#294]
The variable HdWd_SourceofReport_v1r0 (concept ID 764403541) is showing as both a string and integer in dev, so the table is no longer flat. It's showing as a string for sites where the value is null (see image). This is for multiple sites, not just 13 (NCI). 

<img width="686" alt="integer string" src="https://user-images.githubusercontent.com/76711181/155563910-ce3c5db7-7336-4ca6-9548-0d8a2005ae8d.png">

**Comment by brotzmanmj** [comment]
@abhinavjonnada82 Please address this one as high priority as it affects the data structure for the refusal/withdrawal data. Per Nicole: This is a format issue for a regular multiple choice variable. We think this one is straightforward to fix. If any questions, please ask @FrogGirl1123 Thanks!
