### ISSUE TITLE
Pt Summary Pg: Baseline Payment Derived Variables

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#297]
The baseline payment variables have also been derived.  However, we won't be able to test these until all four modules are in the PWA so this one is a lesser priority than the survey and sample derived variables. Note: the concept IDs have not been added to the master data dictionary yet but we know they exist in a csv file. Madhuri @mnataraj92 should be able to point you to them. These are the derived vars that are updated in real time from firestore.

Participant Summary Page: Baseline **Payment**
For the Baseline Payment: 
1. "Item" will remain "n/a"
2. Add derived vars for "status", "date", and "setting"
3. Add "refused" var - this is not a refusal/withdrawal that appears on the participant withdrawal page. This var is sent to us by NORC for "Refused Payment"
4.  Add derived vars for "extra" - this will be eligible vs. not eligible

**Comment by brotzmanmj** [comment]
This has been tested in dev.
