### ISSUE TITLE
Move error message on Pt Lookup

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#30]
On the Pt Lookup screen, if you enter a name and hit 'enter' on your keyboard, you can't see the error message that says 'The participant with entered search criteria not found!' because it appear at the bottom of the screen. Need to move the message to somewhere the user will see it. I suggest in the space underneath the search field for Connect ID but open to suggestions.

**Comment by abhinavjonnada82** [comment]
Space underneath the search field for Connect ID works well but in the future if we decide to add few more fields under Concept ID. Then the error message would go down and would like current scenario.
If there wouldn't be any fields on the concept ID I'm happy to move the alert to Concept ID column.
Suggestion: Maybe we could have an alert banner on top or bottom of the fields?
LMK what you think!

**Comment by brotzmanmj** [comment]
An error message on top of the fields would be good so long as it's visible no matter where you are on the page.

**Comment by abhinavjonnada82** [comment]
Done.

<img width="1356" alt="Screen Shot 2021-04-07 at 12 32 26 PM" src="https://user-images.githubusercontent.com/30497847/113901911-519f8300-979d-11eb-91e3-f737508c78bc.png">
