### ISSUE TITLE
Metrics/Home: Add additional metrics for #active, #verified, response ratio, all baseline activities

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#304]
Please add 3 additional metrics to the very top of the metrics/home page. These should be displayed as a large number with the label underneath it. If possible, all 3 should fit in one row across the top.

(1) Active Recruits more prominently (just the number)
Display as:
NUMBER
Active Recruits
_where number=#active recruits_

(2) Verified Participants more prominently (just a number) and Response Ratio of Verified Participants out of Active and Passive Recruits (percent)
Display as:
NUMBER
Verified Participants
Response Ratio: PERCENT(%)
_where number=#verified participants and PERCENT% ratio=(#verified participants)/(#active+#passive)_
can we also have a hover over "Response Ratio:" where when you hover over it says "out of Active and Passive Recruits"?

(3) Completed Baseline Activities (number and percent) 
Display as:
NUMBER (PERCENT%)
Completed Baseline Activities
Among Verified Participants
_where number=#verified participants that completed all 4 modules and all 3 baseline samples and %=(#verified participants that completed all 4 modules and all 3 baseline samples)/(#total verified participants)_

Please see an example of how these should look on the screen below taken from OCPL specs (ignore "Fully Enrolled Participants", "view details", and "opt outs")
![image](https://user-images.githubusercontent.com/67074735/158626017-6d9e87f0-5d06-46ba-97f5-00178ac98bcc.png)

**Comment by robertsamm** [comment]
@we-ai Hi Warren, additional feedback from Michelle on the third new metric below:

- For the label on the third one for completed baseline activities, instead of 'Completed Baseline Activities Among Verified Participants' have it say ‘Verified Participants who Completed Baseline Survey and Samples’. 
- Keep the hover the same as it is.
- And for the percentage, instead of displaying it next to the number, display it below the number (similar to the response rate on the adjacent metric) and have it say Completion Ratio: X.X%

Otherwise, I think these look great and like how they filter too.

**Comment by robertsamm** [comment]
Hello @we-ai, looking at the Verified Pts who Completed Baseline Survey and Samples metric compared to the CSV file of recruitment data- it does not look like this # is being calculated correctly. 

In the CSV file I can see that there should only be **4** participants who are all three: (1) verified; (2)all 4 modules =submitted (BOH, MRE, SAS, _and_ LAW modules); _and_ (3) all 3 blood, urine, and mouthwash collections =yes. 

Right now the metric is showing as 9 instead of 4. I am wondering if this is only counting those who donated all 3 samples and not taking into account the surveys because the # of verified pts who completed all 3 biospecimens is also 9 right now.

[image](https://user-images.githubusercontent.com/67074735/164062668-b8068c7d-b9d6-4870-a468-dbde56460317.png)

**Comment by we-ai** [comment]
PRs for above feedback: 
- backend: https://github.com/episphere/dashboard/pull/342
- frontend: https://github.com/episphere/connectFaas/pull/153
