### ISSUE TITLE
Fix histogram counts in Current status in workflow 

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#33]
For active recruits, current status in workflow shows 20 active recruits in upper left corner from more than 20 if you add up all the people in the histogram. Is it double counting some people in more than one category? And the Total recruits 'current status in workflow' seems to be undercounting people (has less than 20 in the histogram bars and fewer verified than in the active recruits).

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by robertsamm** [comment]
@abhinavjonnada82 most of the counts look right, except it looks like the count is off in the histogram for total recruits. 
Active verification complete bar = 21
Passive verification complete bar = 6
So the total recruits verification complete should = 27 not 28. 

![image](https://user-images.githubusercontent.com/67074735/116451440-7631cc80-a82a-11eb-9987-0d0543d90259.png)
![image](https://user-images.githubusercontent.com/67074735/116451573-a7aa9800-a82a-11eb-8bed-cd693387b00c.png)
![image](https://user-images.githubusercontent.com/67074735/116451626-ba24d180-a82a-11eb-82d8-f109c30dcbcf.png)

**Comment by abhinavjonnada82** [comment]
![Screen Shot 2021-04-29 at 11 06 19 AM](https://user-images.githubusercontent.com/30497847/116573594-f152bb80-a8da-11eb-97b4-39f402bd5651.png)

**Comment by abhinavjonnada82** [comment]
<img width="1767" alt="Screen Shot 2021-05-13 at 12 01 43 PM" src="https://user-images.githubusercontent.com/30497847/118171519-4cb39c00-b3f9-11eb-875d-a7edf1005409.png">
<img width="1182" alt="Screen Shot 2021-05-13 at 12 02 07 PM" src="https://user-images.githubusercontent.com/30497847/118171525-4f15f600-b3f9-11eb-91e3-6bd42f8578e7.png">

**Comment by robertsamm** [comment]
@abhinavjonnada82 Looking at the NCI dashboard, counts still seem off.
It's showing there are 30 active recruits when it looks like there is 38 based on the histogram counts. And showing 7 passive recruits when it looks like there are 18 in the histogram.
![image](https://user-images.githubusercontent.com/67074735/118172879-e3cd2380-b3fa-11eb-9188-6f05cd0932da.png)
![image](https://user-images.githubusercontent.com/67074735/118173026-14ad5880-b3fb-11eb-9c27-a419057dcc45.png)

**Comment by robertsamm** [comment]
@abhinavjonnada82 Just looked at the pie charts for NCI dshbrd and the %'s still don't match. Can we take the the %'s off the hover?

![image](https://user-images.githubusercontent.com/67074735/118173206-44f4f700-b3fb-11eb-9e65-7328fab5b500.png)

**Comment by robertsamm** [comment]
@abhinavjonnada82 This looks like it is working correctly for the parent site. Closing issue. Thanks!

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 KPCO, Sanford, and Marshfield look good (although I didn't check the demographics).  Health Partners looks good until you get the totals panels then the count, funnel and histogram don't all match. The numbers for "All" are wildly off among the histograms, the counts and the funnels.

**Comment by abhinavjonnada82** [comment]
For parent participant:

![Screen Shot 2021-05-20 at 10 58 15 AM](https://user-images.githubusercontent.com/30497847/119001890-635a7580-b95a-11eb-9b87-b8deb5049d87.png)
![Screen Shot 2021-05-20 at 10 58 20 AM](https://user-images.githubusercontent.com/30497847/119001897-65bccf80-b95a-11eb-8a19-e71faf4b1a71.png)
![Screen Shot 2021-05-20 at 10 58 26 AM](https://user-images.githubusercontent.com/30497847/119001909-681f2980-b95a-11eb-8537-962e298afd3d.png)
![Screen Shot 2021-05-20 at 10 58 36 AM](https://user-images.githubusercontent.com/30497847/119001917-6a818380-b95a-11eb-80ee-6752b5f8b32f.png)
![Screen Shot 2021-05-20 at 10 58 41 AM](https://user-images.githubusercontent.com/30497847/119001925-6c4b4700-b95a-11eb-9b77-c3e86f630aa2.png)

For Funnels:![Screen Shot 2021-05-20 at 10 59 49 AM](https://user-images.githubusercontent.com/30497847/119002038-82f19e00-b95a-11eb-9248-ea387cc484c3.png)

**Comment by abhinavjonnada82** [comment]
Active/Passive & Total recruits count:
![Screen Shot 2021-05-20 at 11 01 08 AM](https://user-images.githubusercontent.com/30497847/119002266-b8968700-b95a-11eb-8fc6-16435bb88fbb.png)
