### ISSUE TITLE
Undefined/email variable appearing on all participants pg

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#348]
Hi @abhinavjonnada82 the 'email' variable that was removed from all 3 tiers is showing up again in stage and prod. It looks like its correctly missing on dev. On stage it is showing up as 'undefined' and on prod as 'email'. Can you please re-remove this var from stage and prod?

Stage:
![image](https://user-images.githubusercontent.com/67074735/165379212-e65509d4-205e-4a8f-bcb4-61ab9d231da6.png)

Prod:
![image](https://user-images.githubusercontent.com/67074735/165379101-474adef5-1273-464c-ba4c-8cf0e9d3a9cb.png)

**Comment by abhinavjonnada82** [comment]
@robertsamm Removed from Stage & this issue would be fixed in the next prod deployment.
