### ISSUE TITLE
Point to real HIPAA variables on Participant Summary screen

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#35]
Row containing HIPAA variables maybe it pointing to placeholder variables? Here are the actual variable names for these:
RcrtCS_HIPAAAuth_v1r0
RcrtCS_HIPAAAuthDt_v1r0
RcrtCS_HIPAAVer_v1r0

**Comment by abhinavjonnada82** [comment]
I believe I'm pointing to the right variables. Is it showing some error for one of the participants?

**Comment by brotzmanmj** [comment]
The hipaa variables are showing on the pt summary for all the participants I checked as 'not submitted'.  It is possible the problem is that the variables aren't being populated in the data. Can you check with Nicole and Madhuri?

**Comment by FrogGirl1123** [comment]
I'll check the back and see if these variables are being populated.

**Comment by FrogGirl1123** [comment]
None of the 3 concept IDs for the variables listed by Michelle are in the Participants data table in BigQuery.  It looks like they are either not being saved or are not being collected by the PWA.  I was able to pull up the variables associated with Consent, so far I'm only showing 2 consented individuals.

**Comment by abhinavjonnada82** [comment]
Variables aren't being collected on the back end.

**Comment by brotzmanmj** [comment]
I believe Brian is working on a fix for this?

**Comment by abhinavjonnada82** [comment]
I can check with him
