### ISSUE TITLE
Phone number field on Participant Lookup

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#37]
For the phone number field in the participant lookup, it seems you need to enter the phone number as just digits, without parenthesis or dashes. Can we add that instruction to the lookup screen, maybe show the expected format in the box itself?

**Comment by abhinavjonnada82** [comment]
Would something like this do on the input of phone number:
<img width="644" alt="Screen Shot 2021-04-12 at 11 28 30 AM" src="https://user-images.githubusercontent.com/30497847/114420315-36a88680-9b82-11eb-9793-5e4feed3b258.png">

**Comment by brotzmanmj** [comment]
Yes, that instruction would help

**Comment by abhinavjonnada82** [comment]
<img width="712" alt="Screen Shot 2021-04-12 at 12 33 59 PM" src="https://user-images.githubusercontent.com/30497847/114429407-5c865900-9b8b-11eb-9c25-b79720514c7e.png">
