### ISSUE TITLE
Pagination/Filtering Updates

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#378]
Please make these updates to the pagination/filtering 
1. Instead of being able to select 10, 25, 50, etc pages let's default the # of records displayed on the page to 50 only
2. Please change the date filter to filter on the variable for 'verification status time' instead of 'time recruitment type assigned'. We don't need the recruit type date but it would be a lot more helpful to filter on the date/time of verification
3. Please keep the site filter and the active/passive filter

Fixes:
1. Please fix the issues that are causing the filters and/or the fields at the top of the screen to go away when you select previous/next buttons
2. Please fix the previous/next buttons so that all of the filters and fields at the top that are selected are retained when you select previous/next (this happens on both the 'all participants' list and the other lists such as the 'verified participants' list
3. Please fix the issue that is causing the filtered list to not be filtered when adding a new field
4. All the selected filters and fields that are selected need to remain steady when you add a new field/filter/select next page

Related Issues (keeping these together so we can close them out all together):
#288, #289, #290

**Comment by abhinavjonnada82** [comment]
Deployed on PROD.
