### ISSUE TITLE
Navigating from Pt Summary to Pt Details

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#38]
If I've selected a participant and then i go to the Pt Summary page, it doesn't let me go back to the Pt Details page for that person. If I click Pt Details, it tells me I need to search for a participant first. What do you suggest to fix this?

**Comment by brotzmanmj** [comment]
Similar thing happens if I'm on the Pt Details page, it doesn't let me click on the Participant Lookup to search for a new participant.

**Comment by abhinavjonnada82** [comment]
Issue has been addressed in PR #40.

**Comment by brotzmanmj** [comment]
Can you check navigation from Pt Details back to Pt Lookup? It won't let me do that.

**Comment by abhinavjonnada82** [comment]
> Can you check navigation from Pt Details back to Pt Lookup? It won't let me do that.

This PR should take care of it #41

**Comment by brotzmanmj** [comment]
Hmm, still doesn't let me do it

**Comment by abhinavjonnada82** [comment]
The PR hasn't been merged yet. So once its merged, you can test it.
