### ISSUE TITLE
Fields listed on All Participants page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#43]
On the 'All participants' page as well as the 'cannot be verified' page and the 'not yet verified' page, among the list of variables floating at the top there are a few that look like code for example D_726699695, and there are others like that. I'm not sure what these are supposed to be, but when you click on them to add them to the table, they show some sort of code. Can you find out what they are and either fix what they are showing or remove them?

Also please add the variable for 'Study ID' to the list of variables that appears among the many above the tables for each of these filtered reports.

**Comment by robertsamm** [comment]
@abhinavjonnada82 it looks like the issue with the random D_# variables are fixed. But I don't see the variable 'Study ID' in the list of floating variables. Can you please add this?

**Comment by robertsamm** [comment]
@abhinavjonnada82 Also, for the variables that are automatically listed in the variable row but are also listed in the floating variables list above, can they all be highlighted to show they're in the row? It looks like Connect_ID does this but the other variables such as Birth Month, Birth Day, Birth Year, and Preferred email are not automatically highlighted. Example below.
![image](https://user-images.githubusercontent.com/67074735/114936772-e09a4400-9e0a-11eb-95fc-59ef52f97371.png)

**Comment by abhinavjonnada82** [comment]
> @abhinavjonnada82 it looks like the issue with the random D_# variables are fixed. But I don't see the variable 'Study ID' in the list of floating variables. Can you please add this?

I fixed the D_# issue, I'm not sure wether study id is available on the backend. Let me check on it once!

About highlight let me look into it and I'll get back to you.

**Comment by brotzmanmj** [comment]
I agree with your suggestion. thanks for pointing that out.

**Comment by abhinavjonnada82** [comment]
This PR takes care of duplicate columns:
https://github.com/episphere/dashboard/pull/52
