### ISSUE TITLE
Change to new variables for Status on Pt Details and Summary headers

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#44]
Nicole and Madhuri created two new variables to replace the one 'Status' variable currently in the header of the Pt Details and Pt Summary screens. Please remove existing variable and add these two:

Enrollment Status (variable name SMMet_EnrollStatus_v1r0)
Participation Status (variable name SMMet_PartStatus_v1r0)

**Comment by abhinavjonnada82** [comment]
Participation Status is done. Waiting on Enrollment Status.

**Comment by brotzmanmj** [comment]
Decided to remove enrollment status variable and reconsider it's construction and need at later time. Confirmed it has been removed.
