### ISSUE TITLE
Fix Collection dates for clinical blood and urine

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#446]
The variables for Collection Date on Participant Summary page for clinical blood and urine are separate variables now for research vs clinical. Please update.

**Comment by abhinavjonnada82** [comment]
Clinical:
<img width="1785" alt="Screen Shot 2022-11-09 at 9 57 05 AM" src="https://user-images.githubusercontent.com/30497847/200890620-47d70f8f-67d3-4816-843d-2bf73d0ab233.png">
<img width="1792" alt="Screen Shot 2022-11-09 at 9 54 00 AM" src="https://user-images.githubusercontent.com/30497847/200890661-c6806acd-73ad-4ffe-91d8-97a4e19e9c9f.png">

Research:
<img width="1791" alt="Screen Shot 2022-11-09 at 10 20 50 AM" src="https://user-images.githubusercontent.com/30497847/200890742-96e3aa89-7394-4498-8b51-68a727be57f3.png">

**Comment by brotzmanmj** [comment]
Hi @abhinavjonnada82 For the mouthwash collected on the Research example, the Setting is showing as N/A but should be Research. Can you check that? Otherwise looks good.

**Comment by abhinavjonnada82** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/30497847/202262432-b7bf5eaf-69b5-431a-85fd-8da63f607de1.png)
