### ISSUE TITLE
Update notifications scheduling function

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/dashboard#448]
Previously, we implemented a "Connect_ID" option for notifications (which allowed UofC to send scheduling reminders with a unique ID)

This looked something like: https://connect-uchicago.timetap.com?externalUserName=${Connect_ID}

Going forwards this should change to no longer use or accept Connect_ID but use/accept "token"

This would look something like: https://connect-uchicago/timetap.com?externalUserName=${token}
Or for Henry Ford something like: https://phs.hfhs.org/Connect/home?token={token}

**Comment by depietrodeanna** [comment]
@depietrodeanna to plug https://phs.hfhs.org/Connect/home?token=${token} into dev email notification specs and test.
@abhinavjonnada82

**Comment by depietrodeanna** [comment]
Moved to prod
