### ISSUE TITLE
Delete search text box on the Participant table page

### ISSUE THREAD

**Issue by dbakumar** [episphere/dashboard#45]
Steps to recreate : 
1. Login to Study Manager Dashboard and  Click All participant menu link
2.  the search text box shows above Participant table on right top 
3.  Enter any participant name and click search icon
4.  No change happened

**Comment by brotzmanmj** [comment]
Abhinav, is the search functionality on the All Participants page supposed to work and is just broken, or was this a planned element that is a placeholder but never actually got programmed?

**Comment by brotzmanmj** [comment]
We discussed at meeting on Monday 5/17 with Bhaumik and Hui and agreed this search box should be removed

**Comment by abhinavjonnada82** [comment]
Search box removed:
<img width="1743" alt="Screen Shot 2021-06-05 at 3 01 58 PM" src="https://user-images.githubusercontent.com/30497847/120902558-112e7b00-c60f-11eb-9fbc-586fd7466a39.png">
