### ISSUE TITLE
SMDB User Profile not updating DOB at time of update

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#450]
Hi Abhinav, Nina at UChicago reported that they updated the DOB for a recruit in their user profile before verification but the dshbrd didn't reflect the changes when they hit 'save changes'. They think it might just be a delay because they were then able to verify the person which means the corrected DOB was saved to the database and later when they looked at the dshbrd it was displaying the corrected DOB. Can you please look into this? For this scenario the Connect ID was 7638389516 in prod.

**Comment by abhinavjonnada82** [comment]
Resolution: When any field is updated on Participant Details page. 
![Screen Shot 2022-11-16 at 3 17 52 PM](https://user-images.githubusercontent.com/30497847/202285448-82cd2dca-ec89-47d3-9c66-19a66f856948.png)
Updated information is reflected immediately on the fields. But on the top header banner, the participant needs to be re selected from the participants table page to reflect updated information
![Screen Shot 2022-11-16 at 3 20 04 PM](https://user-images.githubusercontent.com/30497847/202285825-d13654bc-3bab-45b5-b306-2d2147a9fea3.png)
