### ISSUE TITLE
Add Study ID, Token, and PIN as search variables on Pt Lookup screen

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#46]
Requested by HP

**Comment by brotzmanmj** [comment]
Request for UChicago team today to also add Token and PIN as search fields on the Participant Lookup screen

**Comment by abhinavjonnada82** [comment]
Was able to implement TOKEN & STUDYID. 
Can't implement PIN as the API is only limited to TOKEN, STUDYID & CONNECTID

**Comment by brotzmanmj** [comment]
Hi @bhaumik55231 @abhinavjonnada82, I guess I need a better understanding of this. Our system generates the PIN and the token at the same time, right? But we can search on the token but not the PIN?

**Comment by brotzmanmj** [comment]
Hi @bhaumik55231 @abhinavjonnada82, I checked with NORC and their agents will not search on PIN so we don't need to add that. Token and study ID will be sufficient. I'm closing the issue, thank you!
