### ISSUE TITLE
Delete preferred mode on Pt Details page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#47]
In user profile question 'How do you prefer that we reach you?', Brian is changing one of the response options from 'Mobile phone' to 'Text message'. Please make sure this change is reflected on the Study Manager dashboard Pt Details page.

**Comment by abhinavjonnada82** [comment]
Brian hasn't made the changes, once he's done. I'll update the issue.

**Comment by brotzmanmj** [comment]
We decided to remove this question from the user profile, so now we need to delete it from the Participant Details page. Please delete Preferred Mode.

**Comment by abhinavjonnada82** [comment]
Deleted Preferred Mode from Participant Details
<img width="1698" alt="Screen Shot 2021-06-05 at 2 58 33 PM" src="https://user-images.githubusercontent.com/30497847/120902450-80f03600-c60e-11eb-8528-3eceb28a57d3.png">
<img width="1261" alt="Screen Shot 2021-06-05 at 2 58 52 PM" src="https://user-images.githubusercontent.com/30497847/120902456-8c436180-c60e-11eb-9faf-95df9b9c3b29.png">
