### ISSUE TITLE
Correct Refusal/Withdrawal Date(s)

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/dashboard#470]
Madhuri to add details

**Comment by mnataraj92** [comment]
When HFHS was testing refusals/withdrawals in dev, they noticed that there was a format mismatch for Concept ID: 123868967 (Date Participant Deceased), where the date was not matching the ISO format indicated in the data dictionary. I spoke with Nicole, and we would like a change to be made in the code so the date for this variable can match the ISO format that's in the dictionary.

**Comment by mnataraj92** [comment]
I just spoke with Nicole and Michelle, and we agreed to leave this as a date variable instead of an ISO format (I will change the format in the dictionary to reflect this). No further changes need to be made.
