### ISSUE TITLE
Reasons for Refusal/Withdrawal on Dashboard

### ISSUE THREAD

**Issue by mnataraj92** [episphere/dashboard#481]
There are a few refusal/withdrawal reasons that may have been assigned different concept IDs (similar to the the handful of opt-out reasons where the code and data dictionary diverged and this was causing some API issues). I was doing some testing in dev for these reasons: 

HdRef_PrivacyG_v1r0  (990579614) 
HdRef_PrivacyH_v1r0 (131458944) 
HdRef_PrivacyI_v1r0 (372303208) 
HdRef_NoInternet_v1r0 (121430614)

These should have populated as 'yes' for Connect ID 7367875780 in dev, but they all show as 'no'. We think this might be because these variables are not pointed to the correct CIDs in the dashboard. Abhinav, could you please double check these variables in dev (and if changes need to be made in dev, they'll need to be applied to the other tiers as well).

In addition, there is a new variable HdRef_Concerned_v1r0 (637147033) that is not listed as one of the refusal/withdrawal reasons in the dashboard. Could you please add this reason to the dashboard as well? I'll also check this one when I test in dev and stage. The text for this reason should say "I am concerned about providing information online". 

Thanks!

**Comment by KELSEYDOWLING7** [comment]
No one has answered has answered yes to any of these reasons in prod either

**Comment by abhinavjonnada82** [comment]
I updated CIDs for reasons mentioned & added a new reason. Changes have been pushed to DEV.

**Comment by mnataraj92** [comment]
@abhinavjonnada82 for some reason unfortunately those reasons are still showing up as "no". I tested it for Connect ID 1770530026 in dev. I'm also still not seeing the new reason HdRef_Concerned_v1r0 (637147033) listed as one of the options for reasons for refusal/withdrawal ("I am concerned about providing information online")

**Comment by abhinavjonnada82** [comment]
@mnataraj92  I was able to test ref/wd & selected the refusal options. On Firestore, the reasons were mapped to yes & also I could see the new refusal option mapped to yes as well. Here's the pt i tested CID: 5041901383
I think you were rendering the old version of SMDB & those reasons were still showing up as "no"

**Comment by mnataraj92** [comment]
Thanks for the update! I'll take another look at it soon and get back to you.

**Comment by mnataraj92** [comment]
Hi @abhinavjonnada82 thanks for looking into this! I retested with a new pt this morning and everything looks as expected! Please let me know when you're able to move the changes to stage and I'll test it.
