### ISSUE TITLE
SMDB - Connect PI Change

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#496]
For the Connect PI change, we have to upload new versions of the site-specific Consent and HIPAA Authorization forms to the PWA and SMDB that have the name of the new PI on them. We'll need to be careful to make sure that anyone consented prior to version 2 receives version 1 in the signed forms and anyone that consents after version 2 gets version 2 in the signed forms. The IRB also changed the versioning structure so Version 1=V1.0 and Version 2=V0.02. The IRB is still reviewing these forms so will need to work with fake test forms in dev for now. 

Consent version: RcrtCS_Version_v1r0
HIPAA version: RcrtCS_HIPAAVer_v1r0

Here's where this is affected on the SMDB:
1. Downloadable signed PDFs for Consent and HIPAA forms on the Participant Summary Page
2. Consent and HIPAA version numbers for the ‘Setting’ field on the Participant Summary Page
3. Consent Version’ and ‘HIPAA Version’ bubble fields on the All Participants page
4. Will need to display current signed versions for anyone who signed the forms prior to
implementation date on the Participant Summary page and new version for anyone who signed
after.

Organizational doc on Box for Connect PI change: https://nih.app.box.com/file/1170318838027

**Comment by robertsamm** [comment]
@cunnaneaq not letting me add you as an assignee so seeing if this will work.

**Comment by robertsamm** [comment]
Related PWA github issue: https://github.com/episphere/connectApp/issues/491

**Comment by abhinavjonnada82** [comment]
This ready for testing & here's a test participant 3217026288

**Comment by abhinavjonnada82** [comment]
Approved Consent & HIPAA v2 forms for other sites are uploaded with signature, name & date coordinates.
