### ISSUE TITLE
Prod pt first name not showing in SMDB

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#524]
Prod participant's (Connect ID: 7371310638.) first name is not showing in SMDB, likely because they entered their first name with special characters: ", (, and ). They entered their first name like this (using my name as an example): "AR" (Amelia). We can see that their name was captured on the consent and HIPAA forms but the first name is showing as an empty field on the SMDB. Can you figure out how we can display the first name?

Please note this is a prod participant so please do not put their first name into this github issue/teams/email or send screenshots of their name.

@abhinavjonnada82, this is not urgent so you can wait to attend to this until you get back or @Davinkjohnson can assign to someone else.

**Comment by robertsamm** [comment]
For some reason I am not able to assign issues in this repository to the 'Site Manager Dashboard' project board anymore?

**Comment by abhinavjonnada82** [comment]
Tony performed a manual PROD change to fix this issue.
