### ISSUE TITLE
Add COVID survey to SMDB Participant Summary

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#528]
Add a row on the Participant Summary page for the COVID survey. Please list is right after the SSN survey. The row should be colored blue, in the same alternating light blue/dark blue pattern.
The information displayed on the row should be:
Timeline = Baseline
Category = Survey
Item = COVID 
Status = Concept ID 793330426
Date = date started Concept ID 268176409 if Status= started (615768760) or date submitted Concept ID 784810139 (if Status= submitted 231311385) 
Setting = N/A
Refused = N/A (we don't have a specific refusal variable for this survey)
Extra = N/A

**Comment by abhinavjonnada82** [comment]
Waiting on a IMS to receive COVID survey to test.

**Comment by abhinavjonnada82** [comment]
> Status = Concept ID 793330426

*Status = Concept ID 220186468

**Comment by abhinavjonnada82** [comment]
![Screenshot 2023-06-22 at 2 39 44 PM](https://github.com/episphere/dashboard/assets/30497847/0466cd95-2e35-446b-83e2-5afa34520d2f)

**Comment by brotzmanmj** [comment]
Thanks Abhinav!

**Comment by Davinkjohnson** [comment]
This was addressed in the June release.
