### ISSUE TITLE
Opt-outs currently blank on metrics page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#53]
@abhinavjonnada82 The opt-outs on the metrics page are currently blank on the study manager dshbrd (see screenshot) and I also couldn't find any in the 'All participants' using the 'pre-consent opt-out' floating variable.

 @FrogGirl1123 @mnataraj92 Did you receive any opt out data from HP? This would have been a separate API push with updates on recruitment status. From what I can tell, it looks like they tested 2 scenarios with opt-outs (https://nih.app.box.com/file/800265999858).

![image](https://user-images.githubusercontent.com/67074735/115303363-831b3580-a131-11eb-9cf1-6465cefa4b59.png)

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by brotzmanmj** [comment]
Has there been any update on the data availability for this issue?
