### ISSUE TITLE
[Bug] User unable to save changes in Participant Detail page

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/dashboard#534]
User in production aren't able to save changes  in Participant Detail page [SMDB]

Console logs
https://gitter.ems.host/_matrix/media/r0/download/gitter.im/dad87902e37d9f39e3a5833e28039bd108556550
https://gitter.ems.host/_matrix/media/r0/download/gitter.im/a1cd307ca50a6ac3b8c475160074a37774ea8163

**Comment by cunnaneaq** [comment]
Tested in stage SMDB - able to update and save name change

**Comment by abhinavjonnada82** [comment]
Prod user confirmed save changes in Participant Details works.
