### ISSUE TITLE
Participant Lookup Issue for UP Updates

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#540]
Found an issue when testing the UP Updates in the SMDB for the 'Participant Lookup' page/ search functionality. After I update first or last name on the Participant Details page, if I go to search the person I can only find them if I search by their old name not their new name. This is occurring for both pre-verification and post-verification edits to user profile. Is the participant search looking up people by consent name not user profile name? If possible, we would like it to search by _both_ consent name and 'current' user profile name for both first and last name.

Ex below:
Connect ID: 7216844004
Original name: Jennifer Roberts
New name: Jennifer Roberts

Searching by new name gave me an error:
![image](https://github.com/episphere/dashboard/assets/67074735/e75fc311-aeb9-43ea-89cc-ddcc2d9513d4)

Searching by old name gave me the correct record with the new name listed:
![image](https://github.com/episphere/dashboard/assets/67074735/1b4ce034-45fe-424f-a20d-1df5c1f8b445)
![image](https://github.com/episphere/dashboard/assets/67074735/000a9e5f-09be-4e10-9751-0f332b71229a)

**Comment by robertsamm** [comment]
@Davinkjohnson #402 seems to be related. It was deployed Aug 2022 and updated the participant search to look on both user profile and consent first and last name. However, this could be a separate issue bc we now need it to search on the latest user profile name change? I noticed the label changes that were mentioned in this issue also are missing from the dashboard. Should I reopen this ticket back up to get these labels back into the all participants page to distinguish UP name fields from consent name fields?

**Comment by abhinavjonnada82** [comment]
@robertsamm I remember working on this. The participant search is performed on consent first + last name. This issue https://github.com/episphere/dashboard/issues/402 was over ridden probably by Filtration & pagination changes. I'll add back the changes. 
I'm looking into this issue.

**Comment by JoeArmani** [comment]
Hi @robertsamm, this is addressed in PR https://github.com/episphere/dashboard/pull/538, and is now live in dev. @abhinavjonnada82 helped me find & understand the source of this issue, and it made sense to address it in the 'multi login' PR I was pushing at the time.

Please test it when you have the time. Thanks.

**Comment by Davinkjohnson** [comment]
This was fully addressed in the July Release.
