### ISSUE TITLE
Add memo for Login Changes+UP Edits in Participant Details page

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#542]
Please add this memo in the 'change login mode/email/phone' section of the Participant Details page to remind staff that they should save any user profile edits before going to change the login mode or login email/phone or the UP edits will not be saved. This pathway is fine as is, don't need to make any updates to let both edits + login changes happen at once, a reminder will suffice. Suggest adding under 'Connect ID' but above 'Change Login Mode' (if possible). This should be displayed for both pre-verification and post-verification edits so do not need to limit based on verification status. However, since NORC and DCEG staff are the only ones that should be able to make login changes please limit the memo to DCEG and NORC users, if possible. This is a low priority item, does not need to be made before prod push.

Memo:
Save any User Profile edits before making Login Changes
![image](https://github.com/episphere/dashboard/assets/67074735/8cd55180-8017-4f1e-b8b2-a377758dc248)

**Comment by JoeArmani** [comment]
Hi @robertsamm this is addressed in PR https://github.com/episphere/dashboard/pull/538, which also allows participants to have up to one email authentication method and one phone auth method. The 'change login mode' row is gone. Now there are rows for 'email login' and 'phone login' below this newly added reminder. This is live in dev. Here's a screenshot for a quick view:
<img width="917" alt="Screenshot 2023-06-20 at 8 52 03 AM" src="https://github.com/episphere/dashboard/assets/93854858/8838a795-4242-4ded-b0d7-d9987f1036db">

**Comment by robertsamm** [comment]
Thanks @JoeArmani! The memo looks good. I'll plan to test the multiple login changes in more detail today with Madhuri.

**Comment by JoeArmani** [comment]
Closing - this went into prod in the June release.
