### ISSUE TITLE
Blood, Urine, Mouthwash dates not displaying right on Pt Summary page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#550]
Hi, the Date Collected for blood, urine, and mouthwash are not displaying correctly on the SMDB Participant Summary page. The are showing as blank or 'invalid date' or a date/time format that is longer than what is usually diplayed. 

Example in dev: Connect ID 1418242905
Example in prod: Connect ID 4550920061

**Comment by abhinavjonnada82** [comment]
<img width="1277" alt="Screenshot 2023-07-12 at 10 03 41 AM" src="https://github.com/episphere/dashboard/assets/30497847/0eb90597-c110-4a1d-b124-00600598c0dd">

Dev: Connect ID 1418242905
<img width="1629" alt="Screenshot 2023-07-12 at 12 45 33 PM" src="https://github.com/episphere/dashboard/assets/30497847/feb739bf-f3c1-48c8-8afc-d2876f73253f">

**Comment by abhinavjonnada82** [comment]
<img width="1777" alt="Screenshot 2023-07-12 at 12 51 33 PM" src="https://github.com/episphere/dashboard/assets/30497847/9f226e6f-e78a-4609-9136-b7508fc6c8ea">

**Comment by abhinavjonnada82** [comment]
Tested for research participant on stage & no clinical participants on stage

**Comment by abhinavjonnada82** [comment]
Research Participant:
<img width="1489" alt="Screenshot 2023-07-26 at 3 27 06 PM" src="https://github.com/episphere/biospecimen/assets/30497847/a54ce484-e788-4130-9412-72d264f63c5f">

**Comment by abhinavjonnada82** [comment]
Clinical Stage Participant:
<img width="1511" alt="Screenshot 2023-07-26 at 3 30 42 PM" src="https://github.com/episphere/dashboard/assets/30497847/813804c0-b384-4271-850e-8a268bbe652a">

**Comment by brotzmanmj** [comment]
Does this need to be tested further or is this ready for prod?

**Comment by abhinavjonnada82** [comment]
I tested it on stage & is ready for prod.

**Comment by abhinavjonnada82** [comment]
Looks good in prod. Ready to be closed!
