### ISSUE TITLE
Participant summary variables

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#58]
Can you make sure that the participant summary variables are all pointing to the correct variables, that there are no more dummy variables, and the correct responses are being displayed? Please refer to the specs here for the variables and what should be dispalyed: https://nih.app.box.com/file/767799715947

For example, for the baseline surveys the status should show as 'not started', 'started' or 'submitted'. Not 'completed' (=submitted) and not 'N/A'=(not started) as it is showing now.  SSN should be 'None', '4 Digits' or 'All Digits'. and Payments should be 'Issued' and 'Not Issued'

The refusal variables have also been recently added to the data dictionary - can you check those are being pulled correctly? I think the standard response should be 'N' or no if they have not refused and not 'N/A'.

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by abhinavjonnada82** [comment]
**Payments should be 'Issued' and 'Not Issued'**
<img width="1713" alt="Screen Shot 2021-05-03 at 9 21 04 AM" src="https://user-images.githubusercontent.com/30497847/116881140-e5c00700-abf0-11eb-8c54-2ed805de8c40.png">
**baseline surveys the status should show as 'not started', 'started' or 'submitted'**
<img width="1705" alt="Screen Shot 2021-05-03 at 9 21 42 AM" src="https://user-images.githubusercontent.com/30497847/116881219-fc665e00-abf0-11eb-88a2-bb473785eb26.png">
<img width="1724" alt="Screen Shot 2021-05-03 at 9 21 56 AM" src="https://user-images.githubusercontent.com/30497847/116881244-04260280-abf1-11eb-942b-1f0a0cccc67f.png">
**SSN should be 'None', '4 Digits' or 'All Digits'.**
<img width="1707" alt="Screen Shot 2021-05-03 at 9 23 21 AM" src="https://user-images.githubusercontent.com/30497847/116881396-37689180-abf1-11eb-8ba0-e11cdb417c8f.png">

Refused variables have been updated as well.

**Comment by robertsamm** [comment]
@abhinavjonnada82 Hi Abhinav, this looks almost all good to go. On the payments section under "date", it is showing "undefined/undefined/undefined" can you look at what should go here? I'm assuming "N/A"

![image](https://user-images.githubusercontent.com/67074735/117462406-a3623700-af1c-11eb-8035-bf0348fef9f4.png)
for participant:
![image](https://user-images.githubusercontent.com/67074735/117462515-c0970580-af1c-11eb-9708-dfcb822299c1.png)

**Comment by abhinavjonnada82** [comment]
<img width="1206" alt="Screen Shot 2021-05-07 at 3 47 10 PM" src="https://user-images.githubusercontent.com/30497847/117501023-7e38ed00-af4b-11eb-8317-ca8232b3fd26.png">
