### ISSUE TITLE
Point to correct variables for demographics of verified participants

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#75]
Change to variables in the metric for age, sex, and race to point to the de-identified data variables instead of the questionnaire variables. 
The variables are listed in the MVP metrics spreadsheet: https://nih.app.box.com/file/777424345967?s=97oidojrgwv5ff5hnxaw467qlnhv7ihn

Madhuri has put the derivations to harmonize the sites that are sending more detail. Please check with Nicole and Madhuri on these.

**Comment by abhinavjonnada82** [comment]
Updated charts pointing to right variables:
<img width="1761" alt="Screen Shot 2021-07-08 at 12 34 48 AM" src="https://user-images.githubusercontent.com/30497847/124862978-4f0f1e00-df84-11eb-8972-ea349db1c4b7.png">
