### ISSUE TITLE
Account Sign-in Mechanism Variable Wrong on Participants Page

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/dashboard#79]
The response variables that show up in on the Participants page of the Site Manager Dashboard don't match the Master Data Dictionary.  The options should be:
0 = Gmail
1 = Non-Gmail Email
2 = Cell phone

For the participant I'm reviewing Tanja Barton it's listed as "password"

**Comment by brotzmanmj** [comment]
Bhaumik explained why the data are showing the way they are, and there is no need to make any changes. It is correct as is.
