### ISSUE TITLE
Time recruitment type assigned is wrong in the Participant Page of Site Manager Dashboard

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/dashboard#80]
Time recruitment type assigned is 4/13/21 20:13:21 for Participant Tanja Barton.  It should be 5/13/21 20:13:21.  I don't know if this is an issue in Firestore or for the Dashboard.  BigQuery won't show this update until 2am 5/14/21, so I can't check it there until tomorrow morning.

**Comment by brotzmanmj** [comment]
Also Time Consented Submitted is wrong for this participant. It's showing 4/13/21 also, but should be 5/13/21. It is showing wrong on the All Participants list. But on the header of the Participant Details and Participant Summary pages is it showing correctly as 5/13/21. Is it pulling from different source?

**Comment by bhaumik55231** [comment]
What is the participant token?

**Comment by bhaumik55231** [comment]
<img width="421" alt="Screen Shot 2021-05-14 at 2 35 39 PM" src="https://user-images.githubusercontent.com/26577910/118314120-ae3f3d80-b4c1-11eb-8038-023098b31d1b.png">

Those 2 fields show the correct time in Firestore.

**Comment by bhaumik55231** [comment]
<img width="1374" alt="Screen Shot 2021-05-14 at 2 38 13 PM" src="https://user-images.githubusercontent.com/26577910/118314362-09713000-b4c2-11eb-9581-6e92641d3f76.png">

@FrogGirl1123 @brotzmanmj Dashboard is also showing the correct date. Where did you saw those?

**Comment by brotzmanmj** [comment]
![image](https://user-images.githubusercontent.com/53540067/118314517-42a9a000-b4c2-11eb-80ee-2c9418750177.png)

**Comment by brotzmanmj** [comment]
@bhaumik55231 Noticed this for a whole bunch of participants, it's right on the Participant Summary page but wrong on the 'All Participants' list

**Comment by bhaumik55231** [comment]
Tagging @abhinavjonnada82 to make sure that he sees this.

**Comment by bhaumik55231** [comment]
I fixed this issue as Abhinav is on PTO.

**Comment by brotzmanmj** [comment]
Looks good, thanks, will close
