### ISSUE TITLE
A bunch of data on All Participants page seem to be incorrect

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#82]
There are variables among those floating at the top of the 'All Participants' page that display things that don't seem accurate. We need someone to thoroughly check every variable on this page but here are some examples of what Nicole and I are seeing:

Examples: 
Date variables are mostly showing dates that are not accurate 'Participant Consent Date' is showing '20211205' for lots of participants on the list, not sure why.

Time variables like 'Time User profile submitted' are showing the wrong data and time like 4/12/2021 

Variable 'Module 1' when you add it to the table shows a bunch of code, there are probably more like this but I haven't clicked on them all

Variable for Date Withdrew Consent is showing 'No' which doesn't make sense

Variable for Account Sign In Mechanism is showing response labels that are not in the data dictionary ('password', 'google.com', 'phone')- In the master data dictionary the labels are 'Gmail', 'Non-Gmail Email', and 'Cell phone'- we need the labels for all variables to be those from the master data dictionary

Some variables are not listed at the top of this page at all but seems like they should be- examples are Campaign Type, Recruit Type, - what determines which variables appear here? 

Thanks.

**Comment by bhaumik55231** [comment]
Hi @brotzmanmj 

>Variable for Account Sign In Mechanism is showing response labels that are not in the data dictionary ('password', 'google.com', 'phone')- In the master data dictionary the labels are 'Gmail', 'Non-Gmail Email', and 'Cell phone'- we need the labels for all variables to be those from the master data dictionary

'password', 'google.com', 'phone' is what we receive from Google, we can't encode them as concept Ids because it creates technical debt as we don't control them Google controls them. That's why we store them as we receive them.

**Comment by brotzmanmj** [comment]
Hi @bhaumik55231 , Thanks for the explanation. That's super helpful.  In the master data dictionary we have these variables that might all relate to this:
Firebase authentication userid
Firebase authentication email
FIrebase authentication phone
Firebase authentication first and last name
Firebase authentication sign-in mechanism (this is the one mentioned above).
They all have concept IDs in the data dictionary. So does your email suggest that for all of these that we get from Google, we will store what we receive without encoding as concept IDs? 
@FrogGirl1123  Should we change the dictionary to reflect what we receive from Google, and drop the concept IDs? I know Brian is displaying the Sign In Information on the app and I'm not sure if he's referencing the concept IDs or not. Whatever we're doing with these is consistent throughout.

**Comment by bhaumik55231** [comment]
@brotzmanmj We can continue using concepts at question level (e.g ``995036844``) as we already do in the image below, but categorical responses are hard to encode as those are controlled by Google.
<img width="267" alt="Screen Shot 2021-05-17 at 10 37 03 AM" src="https://user-images.githubusercontent.com/26577910/118507229-0a8da180-b6fc-11eb-82b5-a04942e54c29.png">

* Firebase authentication userid - This is an important identifier like the participant token which is used for a lot of internal server-side logic that's why we store it as ``uid`` in the state object.
* Firebase authentication email - we are using concept ``421823980 ``
* FIrebase authentication phone - we are using concept ``348474836``
* Firebase authentication first and last name - we are using concept ``756862764``
* Firebase authentication sign-in mechanism - we are using concept ``995036844``, but the response is stored as what we receive from Firebase/Google.

**Comment by brotzmanmj** [comment]
@bhaumik55231 @FrogGirl1123 Great, so it seems to me the only thing we should change for the sake of consistency is in the Master Data Dictionary remove the Concept IDs associated with the responses of sign-in mechanism and change the responses to password, google.com, and phone. Then all will be in alignment.

**Comment by bhaumik55231** [comment]
> Great, so it seems to me the only thing we should change for the sake of consistency is in the Master Data Dictionary remove the Concept IDs associated with the responses of sign-in mechanism and change the responses to password, google.com, and phone. Then all will be in alignment.

Yes, Indeed.

**Comment by FrogGirl1123** [comment]
@bhaumik55231 @brotzmanmj  Thank you for clarifying, we will update the dictionary accordingly.  I'm going to add Firebase authentication userid to the ID list in the dictionary.
