### ISSUE TITLE
Fix title on Active and Passive Verification Status pie charts

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#83]
The title seems to be confusing some users. Please change to:

Active Recruits Verification Status 
among those with Profile Completed
N= 

Passive Recruits Verification Status
among those with Profile Completed
N=

**Comment by abhinavjonnada82** [comment]
Fixed title for passive & active:
![Screen Shot 2021-05-20 at 10 50 45 AM](https://user-images.githubusercontent.com/30497847/119000896-82a4d300-b959-11eb-97c7-575c4948d930.png)
![Screen Shot 2021-05-20 at 10 53 10 AM](https://user-images.githubusercontent.com/30497847/119000979-96503980-b959-11eb-9f1b-4c522670873f.png)
