### ISSUE TITLE
Remove filter and sort icons from Participant Summary page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#85]
These up/down arrows and filter icon on the left hand side of the Participant Summary page won't be active for launch so please remove.

**Comment by abhinavjonnada82** [comment]
Filter and sort icons removed from Participant Summary page:
<img width="1744" alt="Screen Shot 2021-06-05 at 3 04 02 PM" src="https://user-images.githubusercontent.com/30497847/120902609-45a23700-c60f-11eb-86e6-c8270be3278d.png">
