### ISSUE TITLE
Add revocation, destruction form download to Pt Summary page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#86]
To allow the CCC and the Sites to download the signed HIPAA Revocation Form and the Data Destruction Form, we need to add two rows to the Participant Summary table.
The rows should go at the bottom of the table after the EMR row.
The rows should be same alternating pink colors of the 'Agreements'.

Here is the content.
For the revocation form:
Timeline = Revocation 
Category = Agreement
Item = HIPAA Revoc Form
Status = Signed OR Not signed OR N/A (if HIPAA not revoked then will be N/A; if HIPAA revoked then will be signed or not signed based on variable HdWd_HIPAArevokesign_v1r0)
Date = Date signed (if signed) or N/A otherwise (variable for date signed is HdWd_DateHIPAArevsign_v1r0)
Setting = Form version (if signed) or N/A otherwise (variable HdWd_HIPAArevokedver_v1r0)
Refused = N/A 
Extra = Download Form (here is link to form: https://nih.app.box.com/file/788308493064)

For the destruction form:
Timeline = Destruction
Category = Agreement
Item = Data Destroy Form
Status = Signed OR Not signed OR N/A (if no data destruction requested then will be N/A; if destruction requested then will be signed or not signed based on variable HdWd_Datadestroysign_v1r0)
Date = Date signed (if signed) or N/A otherwise (variable for date signed is HdWd_DateDatadestsign_v1r0)
Setting = Form version (if signed) or N/A otherwise (variable HdWd_DestroyDataVer_v1r0)
Refused = N/A 
Extra = Download Form (here is link to form:  https://nih.app.box.com/file/791341048707?s=bh694xro30hv2d6r8mpkei28mnvvw1sm)

**Comment by brotzmanmj** [comment]
The date that appears on the HIPAA revocation Form and Data Destruction Form below the signature needs to be the date signed, not today's date.

**Comment by abhinavjonnada82** [comment]
HIPAA Revocation & Data Destruction appears only when selected. By default doesn't appear on the screen.
<img width="1746" alt="Screen Shot 2021-06-05 at 2 54 53 PM" src="https://user-images.githubusercontent.com/30497847/120902362-fe677680-c60d-11eb-86fd-d031c87999c1.png">

<img width="1744" alt="Screen Shot 2021-06-05 at 2 56 08 PM" src="https://user-images.githubusercontent.com/30497847/120902397-2b1b8e00-c60e-11eb-91e7-eb2551a2084a.png">

**Comment by brotzmanmj** [comment]
I'd like to wait to close this until the testing with Deanna is done to make sure this is working as expected, and until we add the icons
