### ISSUE TITLE
Connect ID search on Participant Lookup not working

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#87]
Connect IDs on the Participant Lookup isn't finding a record though there is one in the system.
Examples
Connect ID 
9978972635
2467808328
8186974651

**Comment by abhinavjonnada82** [comment]
![Screen Shot 2021-05-20 at 10 51 57 AM](https://user-images.githubusercontent.com/30497847/119000782-6acd4f00-b959-11eb-86de-9ea8f7b33c5a.png)

![Screen Shot 2021-05-20 at 10 54 54 AM](https://user-images.githubusercontent.com/30497847/119001265-d2839a00-b959-11eb-977b-06eb789c9ebb.png)
![Screen Shot 2021-05-20 at 10 54 24 AM](https://user-images.githubusercontent.com/30497847/119001177-c0a1f700-b959-11eb-85cc-4faaf63502d8.png)
