### ISSUE TITLE
Recruitment Type showing Concept ID 180583933

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#88]
On the All Participants table, Recruitment Type is showing concept ID 180583933 instead of the response code 'Not Active'

![image](https://user-images.githubusercontent.com/53540067/118533486-22721f00-b716-11eb-96af-e1f219d6a4f8.png)

**Comment by abhinavjonnada82** [comment]
Mapped concept ID to variable name:
<img width="1752" alt="Screen Shot 2021-06-05 at 2 59 28 PM" src="https://user-images.githubusercontent.com/30497847/120902469-a2e9b880-c60e-11eb-8b0f-eef87348272d.png">

**Comment by brotzmanmj** [comment]
I know this is picky, but can we have it say 'Not active' instead of 'Inactive', to match the Master Data Dictionary?

**Comment by abhinavjonnada82** [comment]
ofc no worries.
<img width="1714" alt="Screen Shot 2021-06-07 at 10 40 23 AM" src="https://user-images.githubusercontent.com/30497847/121036467-c5014900-c77c-11eb-9860-8f7b196eb81c.png">
