### ISSUE TITLE
Exclude 'Not Yet Active' from Total metrics

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#91]
On the 'Total' metrics row on the dashboard, exclude those with Recruitment Type = Not Yet Active. This is one reason the 'Total' metrics are inaccurate (they are not equaling the sum of the metrics in the rows about with are Active + Passive).

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 I think Madhuri has shared with you all the associated changes for the metrics.  If you have any follow-up questions, please reach out to her
